name: litsim

on:
  push:
    branches: [main]
    paths:
      - "simulator/**"
      - ".github/workflows/ci-litsim.yml"
  pull_request:
    branches: [main]
    paths:
      - "simulator/**"
      - ".github/workflows/ci-litsim.yml"

jobs:
  go-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: simulator
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache-dependency-path: simulator/go.sum
      - run: go test ./...
